// packages/angular-devextreme/src/lib/components/cnx-date-box/cnx-date-box.component.ts
import {
  ChangeDetectorRef,
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
  ViewChild,
} from '@angular/core';
import { DxDateBoxComponent } from 'devextreme-angular';
import { ValueChangedEvent } from 'devextreme/ui/date_box';
import { dxCalendarOptions } from 'devextreme/ui/calendar';

// fallback utility for formatting without moment dependency
function formatDate(date: Date | string | null | undefined): string | null {
  if (!date) return null;
  const d = new Date(date);
  if (isNaN(d.getTime())) return null;
  
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

@Component({
  selector: 'cnx-date-box',
  templateUrl: './cnx-date-box.component.html',
  styleUrl: './cnx-date-box.component.css',
  standalone: false,
})
export class CnxDateBoxComponent implements OnInit {
  @ViewChild('dateBox') public dateBox!: DxDateBoxComponent;

  @Input('id') public id: string = '';
  @Input('name') public name: string = '';
  @Input('placeholder') public placeholder: string = '';
  @Input('minDate') public minDate: Date | string | undefined;
  @Input('maxDate') public maxDate: Date | string | undefined;
  @Input('width') public width: number | string = 110;

  @Input('value')
  set value(val: string | null | Date) {
    if (!val) {
      this._value = null as any;
      return;
    }
    this._value = val?.toString() as any;
  }
  get value(): string {
    return this._value;
  }
  private _value: string = '';

  @Input('disabled') public disabled: boolean = false;

  @Input('disabledDates')
  set disabledDates(val: string[] | null) {
    this._disabledDates = (val || [])
      .map((dateStr) => new Date(dateStr))
      .filter((d) => !isNaN(d.getTime()));
    this._disabledDateSet = this.dateToSet(this._disabledDates);
  }
  get disabledDates(): Date[] {
    return this._disabledDates;
  }
  private _disabledDates: Date[] = [];
  private _disabledDateSet: Set<string> = new Set();

  @Input('format') public format: string = 'dd-MMM-yyyy';
  @Input('calendarOptions') public calendarOptions!: dxCalendarOptions;

  @Input('allowEmpty') public allowEmpty: boolean = true;
  @Input('autoDefault') public autoDefault: boolean = false;

  @Output('onValueChanged') public eventValueChanged = new EventEmitter<ValueChangedEvent>();
  @Output('onEnterKey') public eventEnterKey = new EventEmitter<void>();

  constructor(private cdr: ChangeDetectorRef) {}

  public getClassHolidayCell(cell: any): string {
    if (!cell || !cell.date) return '';
    const cellDateStr = formatDate(cell.date);
    const isHoliday = cellDateStr ? this._disabledDateSet?.has(cellDateStr) : false;
    return isHoliday ? 'holiday-cell !rounded' : '';
  }

  public ngOnInit(): void {
    if (!this.value && !this.disabled && this.autoDefault) {
      setTimeout(() => {
        const todayStr = formatDate(new Date());
        this.onValueChanged({ value: todayStr } as any);
        this.cdr.detectChanges();
      });
    }
  }

  public onValueChanged($event: ValueChangedEvent): void {
    if (!$event.value && !this.allowEmpty) {
      const today = new Date();
      if (this.dateBox && this.dateBox.instance) {
        this.dateBox.instance.option('value', today);
      }
      return;
    }

    let value: string | null = null;
    if (!!$event.value) {
      value = formatDate($event.value);
    }

    let previousValue: string | null = null;
    if (!!$event.previousValue) {
      previousValue = formatDate($event.previousValue);
    }

    this.eventValueChanged.emit({
      ...$event,
      value: value ? value : null,
      previousValue: previousValue ? previousValue : null,
    });

    this.cdr.detectChanges();
  }

  public onEnterKey(): void {
    this.eventEnterKey.emit();
  }

  public isValidChanged($event: boolean): void {
    if (!$event) {
      setTimeout(() => {
        if (this.dateBox && this.dateBox.instance) {
          this.dateBox.instance.reset();
        }
      });
    }
  }

  private dateToSet(dates: Date[]): Set<string> {
    const formattedDates = (dates || [])
      .map((d) => formatDate(d))
      .filter((d): d is string => d !== null);
    return new Set(formattedDates);
  }
}

<dx-date-box
  #dateBox
  [id]="id"
  [name]="name"
  [width]="width"
  [placeholder]="placeholder"
  [min]="minDate"
  [max]="maxDate"
  [displayFormat]="format"
  [disabledDates]="disabledDates"
  [disabled]="disabled"
  [calendarOptions]="calendarOptions"
  [value]="value"
  (onValueChanged)="onValueChanged($event)"
  (onEnterKey)="onEnterKey()"
  (isValidChange)="isValidChanged($event)"
>
  <div *dxTemplate="let cell of 'cell'">
    <div [ngClass]="getClassHolidayCell(cell)">
      {{ cell.text }}
    </div>
  </div>
</dx-date-box>

// packages/react-devextreme/src/lib/components/cnx-date-box/cnx-date-box.tsx
import React, { useEffect, useRef, useMemo, useCallback } from 'react';
import { DateBox } from 'devextreme-react/date-box';
import type { ValueChangedEvent } from 'devextreme/ui/date_box';
import type { EventInfo } from 'devextreme/events';
import type { dxCalendarOptions } from 'devextreme/ui/calendar';

// Fallback utility for formatting without moment dependency
function formatDate(date: Date | string | null | undefined): string | null {
    if (!date) return null;
    const d = new Date(date);
    if (isNaN(d.getTime())) return null;

    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

export interface CnxDateBoxProps {
    id?: string;
    name?: string;
    placeholder?: string;
    minDate?: Date | string;
    maxDate?: Date | string;
    width?: number | string;
    value?: string | null | Date;
    disabled?: boolean;
    disabledDates?: string[] | Date[] | null;
    format?: string;
    calendarOptions?: dxCalendarOptions;
    allowEmpty?: boolean;
    autoDefault?: boolean;
    onValueChanged?: (e: ValueChangedEvent) => void;
    onEnterKey?: () => void;
}

export const CnxDateBox: React.FC<CnxDateBoxProps> = ({
    id = '',
    name = '',
    placeholder = '',
    minDate,
    maxDate,
    width = 110,
    value,
    disabled = false,
    disabledDates = [],
    format = 'dd-MMM-yyyy',
    calendarOptions,
    allowEmpty = true,
    autoDefault = false,
    onValueChanged,
    onEnterKey,
}) => {
    const dateBoxRef = useRef<DateBox>(null);

    const onValueChangedRef = useRef(onValueChanged);
    const onEnterKeyRef = useRef(onEnterKey);
    useEffect(() => {
        onValueChangedRef.current = onValueChanged;
        onEnterKeyRef.current = onEnterKey;
    }, [onValueChanged, onEnterKey]);

    // Parse mapped value
    const mappedValue = useMemo(() => {
        if (!value) return null;
        return new Date(value);
    }, [value]);

    // Compute disabled date set for calendar rendering
    const disabledDateSet = useMemo(() => {
        const dates = (disabledDates || [])
            .map((d) => new Date(d))
            .filter((d) => !isNaN(d.getTime()));

        const formattedDates = dates
            .map((d) => formatDate(d))
            .filter((d): d is string => d !== null);

        return new Set(formattedDates);
    }, [disabledDates]);

    // Handle cell customization (holiday-cell)
    const handleCellTemplate = useCallback(
        (cellData: any, cellIndex: number, cellElement: any) => {
            const cellDateStr = formatDate(cellData.date);
            const isHoliday = cellDateStr
                ? disabledDateSet.has(cellDateStr)
                : false;

            return (
                <span
                    className={
                        isHoliday
                            ? `holiday-cell !rounded ${cellData.text}`
                            : cellData.text
                    }
                >
                    {cellData.text}
                </span>
            );
        },
        [disabledDateSet],
    );

    // Auto Default effect
    useEffect(() => {
        if (
            !mappedValue &&
            !disabled &&
            autoDefault &&
            dateBoxRef.current?.instance
        ) {
            setTimeout(() => {
                dateBoxRef.current?.instance.option('value', new Date());
            }, 0);
        }
    }, [mappedValue, disabled, autoDefault]);

    const handleValueChanged = useCallback(
        (e: ValueChangedEvent) => {
            if (!e.value && !allowEmpty) {
                const today = new Date();
                if (dateBoxRef.current?.instance) {
                    dateBoxRef.current.instance.option('value', today);
                }
                return;
            }

            if (onValueChangedRef.current) {
                let formattedValue: string | null = null;
                if (e.value) {
                    formattedValue = formatDate(e.value);
                }

                let formattedPrevious: string | null = null;
                if (e.previousValue) {
                    formattedPrevious = formatDate(e.previousValue);
                }

                // Propagate event up with mapped yyyy-MM-dd strings
                onValueChangedRef.current({
                    ...e,
                    value: formattedValue ? formattedValue : null,
                    previousValue: formattedPrevious ? formattedPrevious : null,
                });
            }
        },
        [allowEmpty],
    );

    const handleEnterKey = useCallback((e: EventInfo<any>) => {
        if (onEnterKeyRef.current) {
            onEnterKeyRef.current();
        }
    }, []);

    // Keep consistency for invalid typing
    const handleOptionChanged = useCallback((e: any) => {
        if (e.name === 'isValid' && !e.value && dateBoxRef.current?.instance) {
            dateBoxRef.current.instance.option('value', undefined);
        }
    }, []);

    const parsedMinDate = minDate ? new Date(minDate) : undefined;
    const parsedMaxDate = maxDate ? new Date(maxDate) : undefined;

    const elementAttr = useMemo(() => ({ id, name }), [id, name]);

    const mergedCalendarOptions = useMemo(() => {
        return {
            ...calendarOptions,
            cellRender:
                (calendarOptions as any)?.cellRender || handleCellTemplate,
        } as any;
    }, [calendarOptions, handleCellTemplate]);

    return (
        <DateBox
            ref={dateBoxRef}
            elementAttr={elementAttr}
            placeholder={placeholder}
            min={parsedMinDate}
            max={parsedMaxDate}
            width={width}
            value={mappedValue === null ? undefined : mappedValue}
            disabled={disabled}
            displayFormat={format}
            calendarOptions={mergedCalendarOptions}
            onValueChanged={handleValueChanged}
            onEnterKey={handleEnterKey}
            onOptionChanged={handleOptionChanged}
            useMaskBehavior={true}
        />
    );
};

export default CnxDateBox;
