// packages/angular-devextreme/src/lib/components/cnx-check-box-group/cnx-check-box-group.component.ts
import {
    ChangeDetectorRef,
    Component,
    EventEmitter,
    Inject,
    Input,
    OnChanges,
    OnInit,
    Optional,
    Output,
    SimpleChanges,
} from '@angular/core';
import { DxCheckBoxComponent } from 'devextreme-angular';
import { ValueChangedEvent } from 'devextreme/ui/check_box';
import { lastValueFrom } from 'rxjs';
import {
    CheckBoxKey,
    CheckBoxParam,
    CheckBoxViewModel,
} from '../../models/cnx-check-box-group.model';
import { CheckBoxDataProvider } from '../../interfaces/cnx-check-box-group.interface';
import { CHECKBOX_DATA_PROVIDER } from '../../tokens/cnx-check-box-group.token';

@Component({
    selector: 'cnx-check-box-group',
    templateUrl: './cnx-check-box-group.component.html',
    styleUrl: './cnx-check-box-group.component.css',
    standalone: false,
})
export class CnxCheckBoxGroupComponent implements OnInit, OnChanges {
    @Input('id') public id: string = '';
    @Input('name') public name: string = '';

    @Input('value')
    set value(val: string[] | null | undefined) {
        this._value = val ? [...val] : [];
        this.checkMapValue();
    }
    get value(): string[] {
        return this._value;
    }
    private _value: string[] = [];

    @Input('disabled')
    public disabled: boolean = false;

    @Input('direction')
    public direction: 'col' | 'row' = 'col';

    @Input('mode')
    public mode: 'multiple' | 'single' = 'multiple';

    @Input('checkBoxKey')
    public checkBoxKey: CheckBoxKey | null | undefined = null;
    @Input('cascadeBy')
    public cascadeBy: any;

    @Input('ignoreValue')
    public ignoreValue: string[] = [];

    @Input('dataSource')
    set dataSource(items: CheckBoxViewModel[]) {
        this._dataSource = items.map((item) => ({ ...item }));
    }
    get dataSource(): CheckBoxViewModel[] {
        return this._dataSource;
    }
    private _dataSource: CheckBoxViewModel[] = [];

    @Output('onValueChanged')
    public eventValueChanged = new EventEmitter<{ value: string[] }>();

    constructor(
        @Optional()
        @Inject(CHECKBOX_DATA_PROVIDER)
        private service: CheckBoxDataProvider,
        private cdr: ChangeDetectorRef,
    ) {}

    public async ngOnInit(): Promise<void> {
        await this.setupDataSource();
    }

    public async ngOnChanges(changes: SimpleChanges): Promise<void> {
        if (changes['value'] && !changes['value'].firstChange) {
            this.checkMapValue();
        }

        const cascadeChange = changes['cascadeBy'];
        if (cascadeChange && !cascadeChange.firstChange) {
            const isDiff =
                JSON.stringify(cascadeChange.currentValue) !==
                JSON.stringify(cascadeChange.previousValue);
            if (isDiff) {
                await this.setupDataSource();
            }
        }
    }

    public onValueChanged(
        $event: ValueChangedEvent,
        item: CheckBoxViewModel,
    ): void {
        if (this.mode === 'single') {
            if ($event.value === true) {
                this.dataSource.forEach((i) => {
                    if (i.value !== item.value) {
                        i.checked = false;
                    }
                });
            }
        }

        item.checked = $event.value;
        const value = this.dataSource
            .filter((i) => i.checked === true)
            .map((i) => i.value);

        this.eventValueChanged.emit({ value });
    }

    public onClickLabelCheckBox(checkBox: DxCheckBoxComponent): void {
        if (this.disabled) return;
        checkBox.value = !checkBox.value;
    }

    private async setupDataSource(): Promise<void> {
        // 1. In-memory customDataSource
        if (this.dataSource.length > 0 && Array.isArray(this.dataSource)) {
            this.dataSource = this.applyIgnoreValue(this.dataSource);
            this.checkMapValue();
            return;
        }

        // 2. Key-based service
        if (this.checkBoxKey && this.service) {
            const result = await lastValueFrom(
                this.service.getService(this.checkBoxKey, {
                    cascadeBy: this.cascadeBy,
                } as CheckBoxParam),
            );

            console.log('result', result);
            this.dataSource = this.applyIgnoreValue(result);
            this.checkMapValue();
        }
    }

    private applyIgnoreValue(items: CheckBoxViewModel[]): CheckBoxViewModel[] {
        if (!this.ignoreValue?.length) return items;
        return items.filter((item) => !this.ignoreValue.includes(item.value));
    }

    private checkMapValue(): void {
        if (this.dataSource.length > 0) {
            this.dataSource.forEach((item) => {
                item.checked = this._value
                    ? this._value.includes(item.value)
                    : false;
            });
            this.cdr.detectChanges();
        }
    }
}

<div class="cnx-check-box-group" [class.direction-row]="direction === 'row'">
    @for (item of dataSource; track $index) {
        <div class="check-box-item">
            <dx-check-box
                #checkBox
                [id]="
                    'cnx_cbg_' + id + '_' + $index + '_' + item[valueExprOption]
                "
                [name]="
                    'cnx_cbg_' +
                    name +
                    '_' +
                    $index +
                    '_' +
                    item[valueExprOption]
                "
                [(value)]="item.checked"
                [iconSize]="13"
                [disabled]="item.disabled || false || disabled"
                (onValueChanged)="onValueChanged($event, item)"
            ></dx-check-box>
            @if (!!item[displayExprOption]) {
                <span
                    class="check-box-label"
                    [class.clickable]="!item.disabled && !disabled"
                    [class.muted]="item.disabled || disabled"
                    [innerText]="item[displayExprOption]"
                    (click)="onClickLabelCheckBox(checkBox)"
                ></span>
            }
        </div>
    }
</div>

// packages/react-devextreme/src/lib/components/cnx-check-box-group/cnx-check-box-group.tsx
import React, {
    useEffect,
    useState,
    useCallback,
    useMemo,
    useRef,
} from 'react';
import { CheckBox } from 'devextreme-react/check-box';
import type { ValueChangedEvent } from 'devextreme/ui/check_box';
import { useCheckBoxDataProvider } from './cnx-check-box-group.context';
import type {
    CheckBoxKey,
    CheckBoxParam,
    CheckBoxViewModel,
} from './cnx-check-box-group.types';
import './cnx-check-box-group.css';

export interface CnxCheckBoxGroupProps {
    id?: string;
    name?: string;
    value?: string[] | null;
    disabled?: boolean;
    layout?: 'vertical' | 'horizontal';
    mode?: 'multiple' | 'single';
    checkBoxKey?: CheckBoxKey | null;
    cascadeBy?: any;
    ignoreValue?: string[];
    displayExpr?: string;
    valueExpr?: string;
    customDataSource?: any[];
    onValueChanged?: (e: { value: string[] }) => void;
}

export const CnxCheckBoxGroup: React.FC<CnxCheckBoxGroupProps> = ({
    id = '',
    name = '',
    value,
    disabled = false,
    layout = 'horizontal',
    mode = 'multiple',
    checkBoxKey = null,
    cascadeBy,
    ignoreValue,
    displayExpr = 'text',
    valueExpr = 'value',
    customDataSource,
    onValueChanged,
}) => {
    const service = useCheckBoxDataProvider();
    const [rawData, setRawData] = useState<CheckBoxViewModel[]>([]);

    // stable ref
    const valueRef = useRef<string[] | null | undefined>(value);
    const onValueChangedRef = useRef(onValueChanged);
    const modeRef = useRef(mode);

    useEffect(() => {
        valueRef.current = value;
    }, [value]);

    useEffect(() => {
        onValueChangedRef.current = onValueChanged;
    }, [onValueChanged]);

    useEffect(() => {
        modeRef.current = mode;
    }, [mode]);

    // โหลด data
    useEffect(() => {
        const applyIgnore = (items: any[]) =>
            ignoreValue?.length
                ? items.filter((item) => !ignoreValue.includes(item[valueExpr]))
                : items;

        if (customDataSource && Array.isArray(customDataSource)) {
            setRawData(applyIgnore([...customDataSource]));
            return;
        }

        if (checkBoxKey && service) {
            service
                .getService(checkBoxKey, { cascadeBy } as CheckBoxParam)
                .then((result) => setRawData(applyIgnore(result || [])));
        } else {
            setRawData([]);
        }
    }, [checkBoxKey, cascadeBy, customDataSource, ignoreValue, valueExpr]);

    const toggleByKey = useCallback((key: string, checked: boolean) => {
        const current = valueRef.current || [];
        const currentMode = modeRef.current;

        let next: string[];
        if (currentMode === 'single') {
            //single
            next = checked ? [key] : [];
        } else {
            // multiple
            next = checked
                ? current.includes(key)
                    ? [...current]
                    : [...current, key]
                : current.filter((item) => item !== key);
        }

        if (JSON.stringify(current) === JSON.stringify(next)) return;

        onValueChangedRef.current?.({ value: next });
    }, []); // ไม่มี dependency สร้างครั้งเดียว

    const dataSource = useMemo(() => {
        const current = value || [];
        return rawData.map((item) => ({
            ...item,
            checked: current.includes((item as any)[valueExpr]),
        }));
    }, [rawData, value, valueExpr]);

    const externalValueKey = useMemo(
        () => JSON.stringify([...(value || [])].sort()),
        [value],
    );

    return (
        <div
            className={`cnx-check-box-group ${layout === 'horizontal' ? 'horizontal' : 'vertical'}`}
        >
            {dataSource.map((item) => {
                const itemDisabled = item.disabled || disabled;
                const itemKey = (item as any)[valueExpr];
                const domId = `cnx_check_box_group_${id}_${itemKey}`;
                const domName = `cnx_check_box_group_${name}_${itemKey}`;

                return (
                    <div className="check-box-item" key={itemKey}>
                        <CheckBox
                            key={`${domId}_${externalValueKey}`}
                            id={domId}
                            name={domName}
                            defaultValue={item.checked}
                            iconSize={13}
                            disabled={itemDisabled}
                            onValueChanged={(e: ValueChangedEvent) =>
                                toggleByKey(itemKey, e.value)
                            }
                        />
                        {!!(item as any)[displayExpr] && (
                            <span
                                className={`check-box-label ${!itemDisabled ? 'clickable' : ''} ${itemDisabled ? 'muted' : ''}`}
                                onClick={() =>
                                    !itemDisabled &&
                                    toggleByKey(itemKey, !item.checked)
                                }
                            >
                                {(item as any)[displayExpr]}
                            </span>
                        )}
                    </div>
                );
            })}
        </div>
    );
};

export default CnxCheckBoxGroup;
