// packages/angular-devextreme/src/lib/components/cnx-select-box/cnx-select-box.component.ts
import {
    ChangeDetectorRef,
    Component,
    EventEmitter,
    Inject,
    Input,
    OnChanges,
    OnInit,
    Output,
    SimpleChanges,
    ViewChild,
    Optional,
} from '@angular/core';
import { ValueChangedEvent } from 'devextreme/ui/select_box';
import DataSource from 'devextreme/data/data_source';
import { lastValueFrom } from 'rxjs';
import { LoadOptions } from 'devextreme/data';
import { DxSelectBoxComponent } from 'devextreme-angular';
import { SelectBoxDataProvider } from '../../interfaces/cnx-select-box.interface';
import { SELECTBOX_DATA_PROVIDER } from '../../tokens/cnx-select-box.token';
import {
    SelectBoxKey,
    SelectBoxLoadResult,
    SelectBoxParam,
} from '../../models/cnx-select-box.model';

@Component({
    selector: 'cnx-select-box',
    templateUrl: './cnx-select-box.component.html',
    styleUrl: './cnx-select-box.component.css',
    standalone: false,
})
export class CnxSelectBoxComponent implements OnInit, OnChanges {
    constructor(
        private cdr: ChangeDetectorRef,
        @Optional()
        @Inject(SELECTBOX_DATA_PROVIDER)
        private service: SelectBoxDataProvider,
    ) {}

    public ngOnInit(): void {
        this.setupDataSource();
    }

    public ngOnChanges(changes: SimpleChanges): void {
        const change = changes['cascadeBy'];
        if (!!change && !change.firstChange) {
            const { currentValue, previousValue } = change;
            const isChange =
                JSON.stringify(currentValue) !== JSON.stringify(previousValue);
            if (isChange) this.setupDataSource();
        }
        const customChange = changes['customDataSource'];
        if (!!customChange && !customChange.firstChange) {
            this.setupDataSource();
        }
    }

    @ViewChild('selectBox')
    public selectBox!: DxSelectBoxComponent;

    @Input('id') public id: string = '';
    @Input('name') public name: string = '';
    @Input('width') public width: string | number = '100%';
    @Input('placeholder') public placeholder: string = 'Please select...';

    @Input('displayExpr')
    set displayExpr(val: string | null) {
        const _val = val?.toString() || '';
        if (_val && _val !== this._displayExpr) this._displayExpr = _val;
    }
    get displayExpr(): string {
        return this._displayExpr;
    }
    private _displayExpr: string = 'text';

    @Input('valueExpr')
    set valueExpr(val: string | null) {
        const _val = val?.toString() || '';
        if (_val && _val !== this._valueExpr) this._valueExpr = _val;
    }
    get valueExpr(): string {
        return this._valueExpr;
    }
    private _valueExpr: string = 'value';

    @Input('searchExpr')
    set searchExpr(val: string | null) {
        const _val = val?.toString() || '';
        if (_val && _val !== this._searchExpr) this._searchExpr = _val;
    }
    get searchExpr(): string {
        return this._searchExpr;
    }
    private _searchExpr: string = 'dropdownText';

    @Input('dropdownExpr')
    set dropdownExpr(val: string | null) {
        const _val = val?.toString() || '';
        if (_val && _val !== this._dropdownExpr) {
            this._dropdownExpr = _val;
            this._searchExpr = _val;
        }
    }
    get dropdownExpr(): string {
        return this._dropdownExpr;
    }
    private _dropdownExpr: string = 'dropdownText';

    @Input('searchEnabled') public searchEnabled: boolean = true;
    @Input('searchTimeout') public searchTimeout: number = 500;
    @Input('showClearButton') public showClearButton: boolean = true;

    @Input('value')
    set value(val: string | number | null) {
        const _val = val?.toString() ?? '';
        if (_val !== this._value) this._value = _val;
    }
    get value(): string {
        return this._value;
    }
    private _value: string = '';

    public dataSource!: DataSource;
    @Input('customDataSource') public customDataSource?: any;

    @Input('dropdownWidth') public dropdownWidth!: string | number;
    @Input('maxLength') public maxLength: number = 0;
    @Input('disabled') public disabled: boolean = false;
    @Input('cascadeBy') public cascadeBy: any;
    @Input('selectBoxKey') public selectBoxKey:
        | SelectBoxKey
        | null
        | undefined = null;
    @Input('ignoreValue') public ignoreValue!: string[];

    @Output('onValueChanged') public eventValueChanged =
        new EventEmitter<any>();
    @Output('onEnterKey') public eventEnterKey = new EventEmitter<void>();

    private paginate: boolean = true;
    private pageSize: number = 50;
    private clearValueOnCascade: boolean = false;
    public hasInitialValue: boolean = false;

    public onValueChanged($event: ValueChangedEvent): void {
        this.eventValueChanged.emit($event);
        this.cdr.detectChanges();
    }

    public onEnterKey(): void {
        this.eventEnterKey.emit();
    }

    private setupDataSource(): void {
        this.dataSource = new DataSource({
            load: (loadOptions) => this.setupDataSourceOnLoad(loadOptions),
            byKey: (key) => this.setupDataSourceByKey(key),
            paginate: this.paginate,
            pageSize: this.pageSize,
            requireTotalCount: true,
        });

        if (this.clearValueOnCascade && !!this.value && this.selectBox) {
            this.selectBox.value = '';
        }

        this.cdr.detectChanges();
    }

    private async setupDataSourceOnLoad(
        loadOptions: LoadOptions,
    ): Promise<SelectBoxLoadResult> {
        if ((loadOptions?.take ?? 0) === 0) {
            return { data: [], totalCount: 0 };
        }

        // -- Handle In-Memory Custom DataSource --
        if (this.customDataSource && Array.isArray(this.customDataSource)) {
            let filtered = [...this.customDataSource];
            if (loadOptions?.searchValue) {
                const search = loadOptions.searchValue.toString().toLowerCase();
                filtered = filtered.filter(
                    (item) =>
                        (item[this.searchExpr]?.toString() || '')
                            .toLowerCase()
                            .includes(search) ||
                        (item[this.displayExpr]?.toString() || '')
                            .toLowerCase()
                            .includes(search),
                );
            }
            const skip = loadOptions?.skip ?? 0;
            const take = loadOptions?.take ?? 50;
            let pagedData = filtered.slice(skip, skip + take);

            if (this.ignoreValue?.length) {
                pagedData = pagedData.filter(
                    (f) => !this.ignoreValue.includes(f[this.valueExpr]),
                );
            }

            return {
                data: pagedData,
                totalCount: filtered.length,
                hasInitialValue: false,
            };
        }
        // ----------------------------------------

        // 2. Key-based service
        if (this.selectBoxKey && this.service) {
            const result = await lastValueFrom(
                this.service.getService(this.selectBoxKey, {
                    key: this.value,
                    cascadeBy: this.cascadeBy,
                    loadOptions: { ...loadOptions } as LoadOptions,
                } as SelectBoxParam),
            );

            if (this.ignoreValue?.length) {
                result.data = result.data.filter(
                    (f) => !this.ignoreValue.includes(f.value),
                );
            }
            this.hasInitialValue = result.hasInitialValue ?? false;
            return result;
        }

        return { data: [], totalCount: 0 };
    }

    private async setupDataSourceByKey(key: any): Promise<any> {
        if (!key) {
            return [];
        }

        // -- Handle In-Memory Custom DataSource --
        if (this.customDataSource && Array.isArray(this.customDataSource)) {
            const found = this.customDataSource.filter(
                (item) => item[this.valueExpr] === key,
            );
            return found;
        }
        // ----------------------------------------

        // 2. Key-based service
        if (this.selectBoxKey && this.service) {
            const result = await lastValueFrom(
                this.service.getService(this.selectBoxKey, {
                    isByKey: true,
                    key,
                    cascadeBy: this.cascadeBy,
                } as SelectBoxParam),
            );

            return result.data;
        }

        return [];
    }
}

// packages/react-devextreme/src/lib/components/cnx-select-box/cnx-select-box.tsx
import React, {
    useEffect,
    useMemo,
    useRef,
    useState,
    useCallback,
} from 'react';
import { SelectBox } from 'devextreme-react/select-box';
import DataSource from 'devextreme/data/data_source';
import type { EventInfo } from 'devextreme/events';
import type { ValueChangedEvent } from 'devextreme/ui/select_box';
import type { LoadOptions } from 'devextreme/data';
import { useSelectBoxDataProvider } from './cnx-select-box.context';
import type { SelectBoxKey, SelectBoxParam } from './cnx-select-box.types';

export interface CnxSelectBoxProps {
    id?: string;
    name?: string;
    width?: string | number;
    placeholder?: string;
    displayExpr?: string;
    valueExpr?: string;
    searchExpr?: string;
    dropdownExpr?: string;
    searchEnabled?: boolean;
    searchTimeout?: number;
    showClearButton?: boolean;
    value?: string | number | null;
    customDataSource?: any[];
    dropdownWidth?: string | number;
    maxLength?: number;
    disabled?: boolean;
    cascadeBy?: any;
    selectBoxKey?: SelectBoxKey | null;
    ignoreValue?: any[];
    onValueChanged?: (e: ValueChangedEvent) => void;
    onEnterKey?: () => void;
}

export const CnxSelectBox: React.FC<CnxSelectBoxProps> = ({
    id = '',
    name = '',
    width = '100%',
    placeholder = 'Please select...',
    displayExpr = 'text',
    valueExpr = 'value',
    searchExpr = 'dropdownText',
    dropdownExpr = 'dropdownText',
    searchEnabled = true,
    searchTimeout = 500,
    showClearButton = true,
    value = '',
    customDataSource,
    dropdownWidth,
    maxLength = 0,
    disabled = false,
    cascadeBy,
    selectBoxKey = null,
    ignoreValue,
    onValueChanged,
    onEnterKey,
}) => {
    const service = useSelectBoxDataProvider();
    const selectBoxRef = useRef<SelectBox>(null);

    // States
    const [dataSource, setDataSource] = useState<DataSource | null>(null);

    // Refs for stable callbacks
    const valueRef = useRef(value);
    const ignoreValueRef = useRef(ignoreValue);
    const customDataSourceRef = useRef(customDataSource);

    // Track cascading changes securely without inline object identity issues
    const cascadeByStr = JSON.stringify(cascadeBy);

    useEffect(() => {
        valueRef.current = value;
    }, [value]);

    const onValueChangedRef = useRef(onValueChanged);
    const onEnterKeyRef = useRef(onEnterKey);
    useEffect(() => {
        onValueChangedRef.current = onValueChanged;
        onEnterKeyRef.current = onEnterKey;
    }, [onValueChanged, onEnterKey]);

    useEffect(() => {
        ignoreValueRef.current = ignoreValue;
    }, [ignoreValue]);

    useEffect(() => {
        customDataSourceRef.current = customDataSource;
    }, [customDataSource]);

    const paginate = true;
    const pageSize = 50;

    const resolvedSearchExpr = dropdownExpr || searchExpr;

    const setupDataSourceOnLoad = useCallback(
        async (loadOptions: LoadOptions) => {
            if ((loadOptions?.take ?? 0) === 0) {
                return { data: [], totalCount: 0 };
            }

            // Handle custom memory data source
            if (
                customDataSourceRef.current &&
                Array.isArray(customDataSourceRef.current)
            ) {
                let filtered = [...customDataSourceRef.current];
                if (loadOptions?.searchValue) {
                    const search = loadOptions.searchValue
                        .toString()
                        .toLowerCase();
                    filtered = filtered.filter(
                        (item) =>
                            (item[resolvedSearchExpr]?.toString() || '')
                                .toLowerCase()
                                .includes(search) ||
                            (item[displayExpr]?.toString() || '')
                                .toLowerCase()
                                .includes(search),
                    );
                }
                const skip = loadOptions?.skip ?? 0;
                const take = loadOptions?.take ?? 50;
                let pagedData = filtered.slice(skip, skip + take);

                if (ignoreValueRef.current?.length) {
                    pagedData = pagedData.filter(
                        (f) => !ignoreValueRef.current!.includes(f[valueExpr]),
                    );
                }

                return {
                    data: pagedData,
                    totalCount: filtered.length,
                    hasInitialValue: false,
                };
            }

            // Key-based service
            if (selectBoxKey && service) {
                const parsedCascade = cascadeByStr
                    ? JSON.parse(cascadeByStr)
                    : undefined;
                const result = await service.getService(selectBoxKey, {
                    key: valueRef.current,
                    cascadeBy: parsedCascade,
                    loadOptions: { ...loadOptions } as LoadOptions,
                } as SelectBoxParam);

                if (ignoreValueRef.current?.length && result?.data) {
                    result.data = result.data.filter(
                        (f) => !ignoreValueRef.current!.includes(f.value),
                    );
                }
                return result || { data: [], totalCount: 0 };
            }

            return { data: [], totalCount: 0 };
        },
        [
            selectBoxKey,
            service,
            cascadeByStr,
            resolvedSearchExpr,
            displayExpr,
            valueExpr,
        ],
    );

    const setupDataSourceByKey = useCallback(
        async (key: any) => {
            if (!key) return [];

            if (
                customDataSourceRef.current &&
                Array.isArray(customDataSourceRef.current)
            ) {
                return customDataSourceRef.current.filter(
                    (item) => item[valueExpr] === key,
                );
            }

            if (selectBoxKey && service) {
                const parsedCascade = cascadeByStr
                    ? JSON.parse(cascadeByStr)
                    : undefined;
                const result = await service.getService(selectBoxKey, {
                    isByKey: true,
                    key,
                    cascadeBy: parsedCascade,
                } as SelectBoxParam);
                return result?.data || [];
            }

            return [];
        },
        [selectBoxKey, service, cascadeByStr, valueExpr],
    );

    useEffect(() => {
        // Wrap setup inside useEffect to respond to props change
        const ds = new DataSource({
            load: setupDataSourceOnLoad,
            byKey: setupDataSourceByKey,
            paginate,
            pageSize,
            requireTotalCount: true,
        });
        setDataSource(ds);
    }, [setupDataSourceOnLoad, setupDataSourceByKey]);

    const handleValueChanged = useCallback((e: ValueChangedEvent) => {
        if (onValueChangedRef.current) {
            onValueChangedRef.current(e);
        }
    }, []);

    const handleEnterKey = useCallback((e: EventInfo<any>) => {
        if (onEnterKeyRef.current) {
            onEnterKeyRef.current();
        }
    }, []);

    const elementAttr = useMemo(() => ({ id, name }), [id, name]);
    const dropDownOptions = useMemo(
        () => ({ width: dropdownWidth }),
        [dropdownWidth],
    );

    return (
        <SelectBox
            ref={selectBoxRef}
            dataSource={dataSource || undefined}
            elementAttr={elementAttr}
            width={width}
            placeholder={placeholder}
            displayExpr={displayExpr}
            valueExpr={valueExpr}
            searchExpr={resolvedSearchExpr}
            searchEnabled={searchEnabled}
            searchTimeout={searchTimeout}
            showClearButton={showClearButton}
            value={value}
            dropDownOptions={dropDownOptions}
            maxLength={maxLength > 0 ? maxLength : undefined}
            disabled={disabled}
            onValueChanged={handleValueChanged}
            onEnterKey={handleEnterKey}
        />
    );
};

export default CnxSelectBox;
