// packages/angular-devextreme/src/lib/components/cnx-select-box/cnx-select-box.component.ts
import {
    ChangeDetectorRef,
    Component,
    EventEmitter,
    Inject,
    Input,
    OnChanges,
    OnInit,
    Output,
    SimpleChanges,
    ViewChild,
    Optional,
} from '@angular/core';
import { ValueChangedEvent } from 'devextreme/ui/select_box';
import DataSource from 'devextreme/data/data_source';
import { lastValueFrom } from 'rxjs';
import { LoadOptions } from 'devextreme/data';
import { DxSelectBoxComponent } from 'devextreme-angular';
import { SelectBoxDataProvider } from '../../interfaces/cnx-select-box.interface';
import { SELECTBOX_DATA_PROVIDER } from '../../tokens/cnx-select-box.token';
import {
    SelectBoxKey,
    SelectBoxLoadResult,
    SelectBoxParam,
    SelectBoxViewModel,
} from '../../models/cnx-select-box.model';
import { CascadeRule } from '../../models/cnx-cascade-value';

@Component({
    selector: 'cnx-select-box',
    templateUrl: './cnx-select-box.component.html',
    styleUrl: './cnx-select-box.component.css',
    standalone: false,
})
export class CnxSelectBoxComponent implements OnInit, OnChanges {
    constructor(
        private cdr: ChangeDetectorRef,
        @Optional()
        @Inject(SELECTBOX_DATA_PROVIDER)
        private service: SelectBoxDataProvider,
    ) {}

    public ngOnInit(): void {
        this.setupDataSource();
    }

    public ngOnChanges(changes: SimpleChanges): void {
        // ตรวจสอบการเปลี่ยนของ cascadeRule
        const cascadeRuleChange = changes['cascadeRule'];
        if (!!cascadeRuleChange && !cascadeRuleChange.firstChange) {
            const { currentValue, previousValue } = cascadeRuleChange;
            const isChange =
                JSON.stringify(currentValue) !== JSON.stringify(previousValue);
            if (isChange) this.setupDataSource();
        }

        // ตรวจสอบการเปลี่ยนของ cascadeBy
        const change = changes['cascadeBy'];
        if (!!change && !change.firstChange) {
            const { currentValue, previousValue } = change;
            const isChange =
                JSON.stringify(currentValue) !== JSON.stringify(previousValue);
            if (isChange) this.setupDataSource();
        }

        // ตรวจสอบการเปลี่ยนของ customDataSource
        const customChange = changes['customDataSource'];
        if (!!customChange && !customChange.firstChange) {
            this.setupDataSource();
        }
    }

    @ViewChild('selectBox')
    public selectBox!: DxSelectBoxComponent;

    @Input('id') public id: string = '';
    @Input('name') public name: string = '';
    @Input('width') public width: string | number = '100%';
    @Input('placeholder') public placeholder: string = 'Please select...';

    @Input('displayExpr')
    set displayExpr(val: string | null) {
        const _val = val?.toString() || '';
        if (_val && _val !== this._displayExpr) this._displayExpr = _val;
    }
    get displayExpr(): string {
        return this._displayExpr;
    }
    private _displayExpr: string = 'text';

    @Input('valueExpr')
    set valueExpr(val: string | null) {
        const _val = val?.toString() || '';
        if (_val && _val !== this._valueExpr) this._valueExpr = _val;
    }
    get valueExpr(): string {
        return this._valueExpr;
    }
    private _valueExpr: string = 'value';

    @Input('searchExpr')
    set searchExpr(val: string | null) {
        const _val = val?.toString() || '';
        if (_val && _val !== this._searchExpr) this._searchExpr = _val;
    }
    get searchExpr(): string {
        return this._searchExpr;
    }
    private _searchExpr: string = 'text';

    @Input('dropdownExpr')
    set dropdownExpr(val: string | null) {
        const _val = val?.toString() || '';
        if (_val && _val !== this._dropdownExpr) {
            this._dropdownExpr = _val;
            this._searchExpr = _val;
        }
    }
    get dropdownExpr(): string {
        return this._dropdownExpr;
    }
    private _dropdownExpr: string = 'text';

    @Input('searchEnabled') public searchEnabled: boolean = true;
    @Input('searchTimeout') public searchTimeout: number = 500;
    @Input('showClearButton') public showClearButton: boolean = true;

    @Input('value')
    set value(val: string | number | null) {
        const _val = val?.toString() ?? '';
        if (_val !== this._value) this._value = _val;
    }
    get value(): string {
        return this._value;
    }
    private _value: string = '';

    public dataSource!: DataSource;
    @Input('customDataSource') public customDataSource?: any;

    @Input('dropdownWidth') public dropdownWidth!: string | number;
    @Input('maxLength') public maxLength: number = 0;
    @Input('disabled') public disabled: boolean = false;

    @Input('cascadeRule') public cascadeRule: CascadeRule | CascadeRule[];
    @Input('cascadeBy') public cascadeBy: any;

    @Input('selectBoxKey') public selectBoxKey:
        | SelectBoxKey
        | null
        | undefined = null;
    @Input('ignoreValue') public ignoreValue!: string[];

    @Output('onValueChanged') public eventValueChanged =
        new EventEmitter<any>();
    @Output('onEnterKey') public eventEnterKey = new EventEmitter<void>();

    private paginate: boolean = true;
    private pageSize: number = 50;
    private clearValueOnCascade: boolean = false;
    public hasInitialValue: boolean = false;

    public onValueChanged($event: ValueChangedEvent): void {
        this.eventValueChanged.emit($event);
        this.cdr.detectChanges();
    }

    public onEnterKey(): void {
        this.eventEnterKey.emit();
    }

    private setupDataSource(): void {
        this.dataSource = new DataSource({
            load: (loadOptions) => this.setupDataSourceOnLoad(loadOptions),
            byKey: (key) => this.setupDataSourceByKey(key),
            paginate: this.paginate,
            pageSize: this.pageSize,
            requireTotalCount: true,
        });

        if (this.clearValueOnCascade && !!this.value && this.selectBox) {
            this.selectBox.value = '';
        }

        this.cdr.detectChanges();
    }

    private async setupDataSourceOnLoad(
        loadOptions: LoadOptions,
    ): Promise<SelectBoxLoadResult> {
        if ((loadOptions?.take ?? 0) === 0) {
            return { data: [], totalCount: 0 };
        }

        // -- Handle In-Memory Custom DataSource --
        if (this.customDataSource && Array.isArray(this.customDataSource)) {
            let filtered = [...this.customDataSource];
            filtered = this.applyCascadeRule(filtered);
            filtered = this.applyIgnoreValue(filtered);

            if (loadOptions?.searchValue) {
                const search = loadOptions.searchValue.toString().toLowerCase();
                filtered = filtered.filter(
                    (item) =>
                        (item[this.searchExpr]?.toString() || '')
                            .toLowerCase()
                            .includes(search) ||
                        (item[this.displayExpr]?.toString() || '')
                            .toLowerCase()
                            .includes(search),
                );
            }
            const skip = loadOptions?.skip ?? 0;
            const take = loadOptions?.take ?? 50;
            let pagedData = filtered.slice(skip, skip + take);

            return {
                data: pagedData,
                totalCount: filtered.length,
                hasInitialValue: false,
            };
        }
        // ----------------------------------------

        // 2. Key-based service
        if (this.selectBoxKey && this.service) {
            const result = await lastValueFrom(
                this.service.getService(this.selectBoxKey, {
                    key: this.value,
                    cascadeBy: this.cascadeBy,
                    loadOptions: { ...loadOptions } as LoadOptions,
                } as SelectBoxParam),
            );

            result.data = this.applyIgnoreValue(result.data);
            this.hasInitialValue = result.hasInitialValue ?? false;
            return result;
        }

        return { data: [], totalCount: 0 };
    }

    private async setupDataSourceByKey(key: any): Promise<any> {
        if (!key) {
            return [];
        }

        // -- Handle In-Memory Custom DataSource --
        if (this.customDataSource && Array.isArray(this.customDataSource)) {
            let filtered = [...this.customDataSource];
            filtered = this.applyCascadeRule(filtered);
            filtered = this.applyIgnoreValue(filtered);
            const found = filtered.filter(
                (item) => item[this.valueExpr] === key,
            );
            return found;
        }
        // ----------------------------------------

        // 2. Key-based service
        if (this.selectBoxKey && this.service) {
            const result = await lastValueFrom(
                this.service.getService(this.selectBoxKey, {
                    isByKey: true,
                    key,
                    cascadeBy: this.cascadeBy,
                } as SelectBoxParam),
            );

            result.data = this.applyIgnoreValue(result.data);
            return result.data;
        }

        return [];
    }

    private applyCascadeRule(
        items: SelectBoxViewModel[] | any[],
    ): SelectBoxViewModel[] {
        if (
            !this.cascadeRule ||
            this.cascadeBy === undefined ||
            this.cascadeBy === null
        ) {
            return items;
        }

        const rules = Array.isArray(this.cascadeRule)
            ? this.cascadeRule
            : [this.cascadeRule];

        const filtered = items.filter((item) => {
            return rules.every((rule) => {
                let parentVal: any;

                if (
                    typeof this.cascadeBy === 'object' &&
                    this.cascadeBy !== null
                ) {
                    parentVal = this.cascadeBy[rule.parentKey];
                } else if (
                    this.cascadeBy !== undefined &&
                    this.cascadeBy !== null
                ) {
                    parentVal = this.cascadeBy;
                }
                return item[rule.childKey] === parentVal;
            });
        });

        return filtered;
    }

    private applyIgnoreValue(
        items: SelectBoxViewModel[] | any[],
    ): SelectBoxViewModel[] {
        if (!this.ignoreValue?.length) return items;

        return items.filter(
            (item) => !this.ignoreValue.includes(item[this.valueExpr]),
        );
    }
}

// packages/react-mui/src/lib/components/cnx-select-box/cnx-select-box.tsx
import Select from '@mui/material/Select';
import FormControl from '@mui/material/FormControl';
import IconButton from '@mui/material/IconButton';
import ClearIcon from '@mui/icons-material/Clear';
import ArrowDropDown from '@mui/icons-material/ArrowDropDown';
import MenuItem from '@mui/material/MenuItem';

import React, {
    useCallback,
    useEffect,
    useMemo,
    useRef,
    useState,
} from 'react';
import type {
    SelectBoxLoadResult,
    SelectBoxParam,
    SelectBoxViewModel,
} from './cnx-select-box.types';
import { useSelectBoxDataProvider } from './cnx-select-box.context';
import { CascadeRule } from '../cnx-cascade-value.types';
import { ValueChangedEvent } from '../cnx-value-changed.types';

export interface CnxSelectBoxProps {
    id?: string;
    name?: string;
    width?: string | number;
    placeholder?: string;
    displayExpr?: string;
    valueExpr?: string;
    showClearButton?: boolean;
    value?: string | number | null;
    customDataSource?: any[];
    disabled?: boolean;
    cascadeRule?: CascadeRule | CascadeRule[];
    cascadeBy?: any;
    selectBoxKey?: string;
    ignoreValue?: string | string[];
    onValueChanged?: (e: ValueChangedEvent) => void;
    onEnterKey?: () => void;
}

export const CnxSelectBox: React.FC<CnxSelectBoxProps> = ({
    id,
    name,
    placeholder = 'Please select...',
    displayExpr = 'text',
    valueExpr = 'value',
    showClearButton = true,
    value = null,
    customDataSource,
    disabled = false,
    cascadeRule,
    cascadeBy,
    selectBoxKey = null,
    ignoreValue,
    onValueChanged,
    onEnterKey,
}) => {
    const service = useSelectBoxDataProvider();
    const selectBoxRef = useRef<HTMLSelectElement>(null);

    const [dataSource, setDataSource] = useState<SelectBoxLoadResult | null>(
        null,
    );

    // stable ref
    const customDataSourceRef = useRef(customDataSource);

    const valueRef = useRef(value);
    const onValueChangedRef = useRef(onValueChanged);
    const onEnterKeyRef = useRef(onEnterKey);

    useEffect(() => {
        valueRef.current = value;
    }, [value]);

    useEffect(() => {
        customDataSourceRef.current = customDataSource;
    }, [customDataSource]);

    useEffect(() => {
        onValueChangedRef.current = onValueChanged;
    }, [onValueChanged]);

    useEffect(() => {
        onEnterKeyRef.current = onEnterKey;
    }, [onEnterKey]);

    const prevCascadeByRef = useRef(cascadeBy);
    useEffect(() => {
        if (
            JSON.stringify(prevCascadeByRef.current) !==
            JSON.stringify(cascadeBy)
        ) {
            prevCascadeByRef.current = cascadeBy;
            const currentValue = valueRef.current;
            if (
                currentValue !== null &&
                currentValue !== undefined &&
                currentValue !== ''
            ) {
                onValueChangedRef.current?.({
                    previousValue: currentValue,
                    value: null,
                });
            }
        }
    }, [cascadeBy]);

    const applyCascadeRule = useCallback(
        (
            items: SelectBoxViewModel[],
            rule: CascadeRule | CascadeRule[] | undefined,
            by: any,
        ): SelectBoxViewModel[] => {
            if (!rule || by === undefined || by == null) return items;

            const rules = Array.isArray(rule) ? rule : [rule];

            return items.filter((item) =>
                rules.every((r) => {
                    const parentValue =
                        typeof by === 'object' && by !== null
                            ? by[r.childKey]
                            : by;
                    return item[r.childKey] === parentValue;
                }),
            );
        },
        [],
    );

    const applyIgnoreValue = useCallback(
        (
            items: SelectBoxViewModel[],
            ignore: string | string[] | undefined,
        ): SelectBoxViewModel[] => {
            if (!ignore || !ignore.length) return items;
            const ignores = Array.isArray(ignore) ? ignore : [ignore];

            return items.filter((item) => !ignores.includes(item[valueExpr]));
        },
        [valueExpr],
    );

    const setupDataSource =
        useCallback(async (): Promise<SelectBoxLoadResult> => {
            if (
                customDataSourceRef.current &&
                Array.isArray(customDataSourceRef.current)
            ) {
                let filtered = [...customDataSourceRef.current];
                filtered = applyCascadeRule(filtered, cascadeRule, cascadeBy);
                filtered = applyIgnoreValue(filtered, ignoreValue);

                return { data: filtered, totalCount: filtered.length };
            }

            if (selectBoxKey && service) {
                const result = await service.getService(selectBoxKey, {
                    cascadeBy: cascadeBy,
                } as SelectBoxParam);

                result.data = applyIgnoreValue(result?.data, ignoreValue);

                return { data: result.data, totalCount: result.totalCount };
            }

            return { data: [], totalCount: 0 };
        }, [
            selectBoxKey,
            service,
            applyCascadeRule,
            applyIgnoreValue,
            cascadeBy,
            cascadeRule,
            ignoreValue,
        ]);

    useEffect(() => {
        let cancelled = false;
        const loadData = async () => {
            const ds = await setupDataSource();
            if (!cancelled) setDataSource(ds);
        };

        loadData();
        return () => {
            cancelled = true;
        };
    }, [setupDataSource]);

    const handleChange = (newValue: any) => {
        const oldValue = valueRef.current;

        if (oldValue === newValue) return;

        onValueChangedRef.current?.({
            previousValue: oldValue,
            value: newValue,
        });
    };

    const renderIcon = useCallback((iconProp: any) => {
        return <ArrowDropDown titleAccess="Open" {...iconProp} />;
    }, []);

    const renderClearIcon = useCallback(
        () =>
            showClearButton && value ? (
                <IconButton
                    size="small"
                    sx={{ mr: 2 }}
                    onClick={(e) => {
                        e.stopPropagation();
                        handleChange(null);
                    }}
                >
                    <ClearIcon titleAccess="Clear" fontSize="small" />
                </IconButton>
            ) : null,
        [showClearButton, value, handleChange],
    );

    const menuItems = useMemo(() => {
        return dataSource?.data?.map((option) => (
            <MenuItem key={option[valueExpr]} value={option[valueExpr]}>
                {option[displayExpr]}
            </MenuItem>
        ));
    }, [dataSource, valueExpr, displayExpr]);

    const isValueInOptions = useMemo(() => {
        if (!dataSource?.data || value == null || value === '') return false;
        return dataSource.data.some((option) => option[valueExpr] === value);
    }, [dataSource, value, valueExpr]);

    return (
        <FormControl fullWidth size="small">
            <Select
                id={`cnx_select_box_${id}`}
                name={`cnx_select_box_${name}`}
                ref={selectBoxRef}
                value={value ?? ''}
                disabled={disabled}
                onChange={(e) => {
                    handleChange(e.target.value);
                }}
                onKeyDown={(e) => {
                    if (e.key === 'Enter') onEnterKeyRef.current?.();
                }}
                IconComponent={renderIcon}
                endAdornment={renderClearIcon()}
                displayEmpty
            >
                {placeholder && (
                    <MenuItem value="" disabled sx={{ display: 'none' }}>
                        <span className="text-content-1/45">{placeholder}</span>
                    </MenuItem>
                )}
                {value != null && value !== '' && !isValueInOptions && (
                    <MenuItem value={value as any} sx={{ display: 'none' }}>
                        {String(value)}
                    </MenuItem>
                )}
                {menuItems}
            </Select>
        </FormControl>
    );
};

export default React.memo(CnxSelectBox);
