// packages/react-devextreme/src/lib/components/cnx-tag-box/cnx-tag-box.tsx
import React, {
    useEffect,
    useRef,
    useState,
    useCallback,
    useMemo,
} from 'react';
import { TagBox } from 'devextreme-react/tag-box';
import DataSource from 'devextreme/data/data_source';
import type { EventInfo } from 'devextreme/events';
import type { ValueChangedEvent } from 'devextreme/ui/tag_box';
import type { LoadOptions } from 'devextreme/data';
import { useTagBoxDataProvider } from './cnx-tag-box.context';
import type {
    TagBoxKey,
    TagBoxParam,
    TagBoxViewModel,
} from './cnx-tag-box.types';

export interface CnxTagBoxProps {
    id?: string;
    name?: string;
    width?: string | number;
    placeholder?: string;
    displayExpr?: string;
    valueExpr?: string;
    searchExpr?: string;
    dropdownExpr?: string;
    searchEnabled?: boolean;
    searchTimeout?: number;
    showClearButton?: boolean;
    showSelectionControls?: boolean;
    value?: string[] | number[] | null;
    customDataSource?: any[];
    dropdownWidth?: string | number;
    maxLength?: number;
    maxDisplayedTags?: number;
    disabled?: boolean;
    cascadeBy?: any;
    tagBoxKey?: TagBoxKey | null;
    onValueChanged?: (e: ValueChangedEvent) => void;
    onEnterKey?: () => void;
}

export const CnxTagBox: React.FC<CnxTagBoxProps> = ({
    id = '',
    name = '',
    width = '100%',
    placeholder = 'Please select...',
    displayExpr = 'text',
    valueExpr = 'value',
    searchExpr = 'dropdownText',
    dropdownExpr = 'dropdownText',
    searchEnabled = true,
    searchTimeout = 500,
    showClearButton = true,
    showSelectionControls = true,
    value = [],
    customDataSource,
    dropdownWidth,
    maxLength = 0,
    maxDisplayedTags,
    disabled = false,
    cascadeBy,
    tagBoxKey = null,
    onValueChanged,
    onEnterKey,
}) => {
    const service = useTagBoxDataProvider();
    const tagBoxRef = useRef<TagBox>(null);

    // Normalize internal value to string array to match Angular behavior
    const valueStr = JSON.stringify(value);
    const normalizedValue = useMemo(() => {
        return (value || []).map((e) => e.toString());
    }, [valueStr]);

    const normalizedValueRef = useRef(normalizedValue);
    useEffect(() => {
        normalizedValueRef.current = normalizedValue;
    }, [normalizedValue]);

    const customDataSourceRef = useRef(customDataSource);
    const cascadeByStr = JSON.stringify(cascadeBy);
    useEffect(() => {
        customDataSourceRef.current = customDataSource;
    }, [customDataSource]);

    const onValueChangedRef = useRef(onValueChanged);
    const onEnterKeyRef = useRef(onEnterKey);
    useEffect(() => {
        onValueChangedRef.current = onValueChanged;
        onEnterKeyRef.current = onEnterKey;
    }, [onValueChanged, onEnterKey]);

    const [dataSource, setDataSource] = useState<DataSource | null>(null);

    const paginate = true;
    const pageSize = 50;

    const resolvedSearchExpr = dropdownExpr || searchExpr;

    const setupDataSourceOnLoad = useCallback(
        async (loadOptions: LoadOptions) => {
            let fromFilter = loadOptions?.filter
                ?.filter((item: any) => typeof item === 'object')
                .map((item: any[]) => {
                    let index = item?.length - 1 >= 0 ? item?.length - 1 : 0;
                    let i = item[index];
                    return i;
                });

            // Handle In-Memory Custom DataSource
            if (
                customDataSourceRef.current &&
                Array.isArray(customDataSourceRef.current)
            ) {
                let filtered = [...customDataSourceRef.current];
                if (loadOptions?.searchValue) {
                    const search = loadOptions.searchValue
                        .toString()
                        .toLowerCase();
                    filtered = filtered.filter(
                        (item) =>
                            (item[resolvedSearchExpr]?.toString() || '')
                                .toLowerCase()
                                .includes(search) ||
                            (item[displayExpr]?.toString() || '')
                                .toLowerCase()
                                .includes(search),
                    );
                }
                const skip = loadOptions?.skip ?? 0;
                const take = loadOptions?.take ?? 50;
                let pagedData = filtered.slice(skip, skip + take);

                return {
                    data: pagedData,
                    totalCount: filtered.length,
                    hasInitialValue: false,
                };
            }

            // Key-based service
            if (tagBoxKey && service) {
                const parsedCascade = cascadeByStr
                    ? JSON.parse(cascadeByStr)
                    : undefined;
                const result = await service.getService(tagBoxKey, {
                    key: (fromFilter?.length ?? 0) > 0 ? fromFilter : [],
                    cascadeBy: parsedCascade,
                    loadOptions: {
                        ...loadOptions,
                        searchValue: loadOptions.searchValue,
                        take: pageSize,
                    } as LoadOptions,
                } as TagBoxParam);

                const hasInitialValue = result?.hasInitialValue ?? false;

                // Optionally mutate current TagBox instance value if missing loaded dependencies
                if (hasInitialValue && tagBoxRef.current?.instance) {
                    let all = new Set(
                        result.data.map((x: TagBoxViewModel) => x.value),
                    );
                    const safeValue = normalizedValueRef.current.filter((x) =>
                        all.has(x),
                    );
                    tagBoxRef.current.instance.option('value', safeValue);
                }

                return result || { data: [], totalCount: 0 };
            }

            return { data: [], totalCount: 0 };
        },
        [
            tagBoxKey,
            service,
            cascadeByStr,
            pageSize,
            displayExpr,
            resolvedSearchExpr,
        ],
    );

    const setupDataSourceByKey = useCallback(
        async (key: any | string | number) => {
            if (!key) return [];

            if (
                customDataSourceRef.current &&
                Array.isArray(customDataSourceRef.current)
            ) {
                let keys = Array.isArray(key) ? key : [key];
                return customDataSourceRef.current.filter((item) =>
                    keys.includes(item[valueExpr]),
                );
            }

            if (tagBoxKey && service) {
                const result = await service.getService(tagBoxKey, {
                    isByKey: true,
                    key: key,
                } as TagBoxParam);
                return result?.data || [];
            }

            return [];
        },
        [tagBoxKey, service, valueExpr],
    );

    useEffect(() => {
        const ds = new DataSource({
            load: setupDataSourceOnLoad,
            byKey: setupDataSourceByKey,
            paginate,
            pageSize,
            requireTotalCount: true,
        });
        setDataSource(ds);
    }, [setupDataSourceOnLoad, setupDataSourceByKey]);

    const handleValueChanged = useCallback((e: ValueChangedEvent) => {
        if (onValueChangedRef.current) {
            onValueChangedRef.current(e);
        }
    }, []);

    const handleEnterKey = useCallback((e: EventInfo<any>) => {
        if (onEnterKeyRef.current) {
            onEnterKeyRef.current();
        }
    }, []);

    const elementAttr = useMemo(() => ({ id, name }), [id, name]);
    const dropDownOptions = useMemo(
        () => ({ width: dropdownWidth }),
        [dropdownWidth],
    );

    return (
        <TagBox
            ref={tagBoxRef}
            dataSource={dataSource || undefined}
            elementAttr={elementAttr}
            width={width}
            placeholder={placeholder}
            displayExpr={displayExpr}
            valueExpr={valueExpr}
            searchExpr={resolvedSearchExpr}
            searchEnabled={searchEnabled}
            searchTimeout={searchTimeout}
            showClearButton={showClearButton}
            showSelectionControls={showSelectionControls}
            value={normalizedValue}
            dropDownOptions={dropDownOptions}
            maxLength={maxLength > 0 ? maxLength : undefined}
            maxDisplayedTags={maxDisplayedTags}
            disabled={disabled}
            onValueChanged={handleValueChanged}
            onEnterKey={handleEnterKey}
        />
    );
};

export default CnxTagBox;

// packages/angular-devextreme/src/lib/components/cnx-tag-box/cnx-tag-box.component.ts
import {
  ChangeDetectorRef,
  Component,
  EventEmitter,
  Inject,
  Input,
  OnChanges,
  OnInit,
  Output,
  SimpleChanges,
  ViewChild,
  Optional,
} from '@angular/core';
import { DxTagBoxComponent } from 'devextreme-angular';
import DataSource from 'devextreme/data/data_source';
import { lastValueFrom } from 'rxjs';
import { ValueChangedEvent } from 'devextreme/ui/tag_box';
import { LoadOptions } from 'devextreme/data';
import { TagBoxKey, TagBoxParam, TagBoxLoadResult, TagBoxViewModel } from '../../models/cnx-tag-box.model';
import { TagBoxDataProvider } from '../../interfaces/cnx-tag-box.interface';
import { TAGBOX_DATA_PROVIDER } from '../../tokens/cnx-tag-box.token';

@Component({
  selector: 'cnx-tag-box',
  templateUrl: './cnx-tag-box.component.html',
  styleUrl: './cnx-tag-box.component.css',
  standalone: false,
})
export class CnxTagBoxComponent implements OnInit, OnChanges {
  constructor(
    @Optional() @Inject(TAGBOX_DATA_PROVIDER) private service: TagBoxDataProvider,
    private cdr: ChangeDetectorRef
  ) {}

  public ngOnInit(): void {
    this.setupDataSource();
  }

  public ngOnChanges(changes: SimpleChanges): void {
    const change = changes['cascadeBy'];
    if (!!change && !change.firstChange) {
      const { currentValue, previousValue } = change;
      const isChange = JSON.stringify(currentValue) !== JSON.stringify(previousValue);
      if (isChange) this.setupDataSource();
    }
    const customChange = changes['customDataSource'];
    if (!!customChange && !customChange.firstChange) {
      this.setupDataSource();
    }
  }

  @ViewChild('tagBox') public tagBox!: DxTagBoxComponent;

  @Input('id') public id: string = '';
  @Input('name') public name: string = '';
  @Input('width') public width: string | number = '100%';
  @Input('placeholder') public placeholder: string = 'Please select...';
  
  @Input('displayExpr')
  set displayExpr(val: string | null) {
    let _val = val || '';
    _val = _val.toString();
    if (!!_val && _val != this.displayExprOption) this.displayExprOption = _val;
  }
  get displayExpr(): string {
    return this.displayExprOption;
  }
  private displayExprOption: string = 'text';

  @Input('valueExpr')
  set valueExpr(val: string | null) {
    let _val = val || '';
    _val = _val.toString();
    if (!!_val && _val != this.valueExprOption) this.valueExprOption = _val;
  }
  get valueExpr(): string {
    return this.valueExprOption;
  }
  private valueExprOption: string = 'value';

  @Input('searchExpr')
  set searchExpr(val: string | null) {
    let _val = val || '';
    _val = _val.toString();
    if (!!_val && _val != this.searchExprOption) this.searchExprOption = _val;
  }
  get searchExpr(): string {
    return this.searchExprOption;
  }
  private searchExprOption: string = 'dropdownText';

  @Input('dropdownExpr')
  set dropdownExpr(val: string | null) {
    let _val = val || '';
    _val = _val.toString();
    if (!!_val && _val != this.dropdownExprOption) this.dropdownExprOption = _val; // fixed old bug mapping wrong prop
  }
  get dropdownExpr(): string {
    return this.dropdownExprOption;
  }
  private dropdownExprOption: string = 'dropdownText';

  @Input('searchEnabled') public searchEnabled: boolean = true;
  @Input('searchTimeout') public searchTimeout: number = 500;
  @Input('showClearButton') public showClearButton: boolean = true;
  @Input('showSelectionControls') public showSelectionControls: boolean = true;

  @Input('value')
  set value(val: string[] | number[] | null) {
    let _val = val || [];
    _val = _val.map((e) => e.toString());

    if (JSON.stringify(_val) !== JSON.stringify(this._value)) {
      this._value = _val as string[];
    }
  }
  get value(): string[] {
    return this._value;
  }
  private _value: string[] = [];

  public dataSource!: DataSource;
  @Input('customDataSource') public customDataSource?: any;

  @Input('dropdownWidth') public dropdownWidth!: string | number;
  @Input('maxLength') public maxLength: number = 0;
  @Input('maxDisplayedTags') public maxDisplayedTags: number = null as any;
  @Input('disabled') public disabled: boolean = false;
  @Input('cascadeBy') public cascadeBy: any;
  @Input('tagBoxKey') public tagBoxKey: TagBoxKey | null | undefined = null;

  @Output('onValueChanged') public eventValueChanged = new EventEmitter<any>();
  @Output('onEnterKey') public eventEnterKey = new EventEmitter<any>();

  private paginate: boolean = true;
  private pageSize: number = 50;
  public hasInitialValue: boolean = false;

  public onValueChanged($event: ValueChangedEvent): void {
    this.eventValueChanged.emit($event);
    this.cdr.detectChanges();
  }

  public onEnterKey(): void {
    this.eventEnterKey.emit();
  }

  private setupDataSource(): void {
    this.dataSource = new DataSource({
      load: (loadOptions) => this.setupDataSourceOnLoad(loadOptions),
      byKey: (key) => this.setupDataSourceByKey(key),
      paginate: this.paginate,
      pageSize: this.pageSize,
      requireTotalCount: true,
    });
    this.cdr.detectChanges();
  }

  private async setupDataSourceOnLoad(loadOptions: LoadOptions): Promise<TagBoxLoadResult> {
    let fromFilter = loadOptions?.filter?.filter((item: any) => typeof item === 'object').map((item: any[]) => {
      let index = item?.length - 1 >= 0 ? item?.length - 1 : 0;
      let i = item[index];
      return i;
    });

    // -- Handle In-Memory Custom DataSource --
    if (this.customDataSource && Array.isArray(this.customDataSource)) {
      let filtered = [...this.customDataSource];
      if (loadOptions?.searchValue) {
        const search = loadOptions.searchValue.toString().toLowerCase();
        filtered = filtered.filter(
          (item) =>
            (item[this.searchExpr]?.toString() || '').toLowerCase().includes(search) ||
            (item[this.displayExpr]?.toString() || '').toLowerCase().includes(search)
        );
      }
      const skip = loadOptions?.skip ?? 0;
      const take = loadOptions?.take ?? 50;
      let pagedData = filtered.slice(skip, skip + take);

      return { data: pagedData, totalCount: filtered.length, hasInitialValue: false };
    }
    // ----------------------------------------

    if (!this.service) {
      console.warn('CnxTagBox: TAGBOX_DATA_PROVIDER is not provided.');
      return { data: [], totalCount: 0 };
    }

    const result = await lastValueFrom(
      this.service.getService(this.tagBoxKey, {
        key: (fromFilter?.length ?? 0) > 0 ? fromFilter : [],
        cascadeBy: this.cascadeBy ? { ...this.cascadeBy } : undefined,
        loadOptions: {
          ...loadOptions,
          searchValue: loadOptions.searchValue,
          take: this.pageSize,
        } as LoadOptions,
      } as TagBoxParam)
    );

    this.hasInitialValue = result.hasInitialValue ?? false;

    if (this.hasInitialValue && this.tagBox) {
      let all = new Set(result.data.map((x: TagBoxViewModel) => x.value));
      this.tagBox.value = this.value.filter((x) => all.has(x));
    }

    return result;
  }

  private async setupDataSourceByKey(key: any | string | number): Promise<any> {
    if (!key) {
      return [];
    }

    // -- Handle In-Memory Custom DataSource --
    if (this.customDataSource && Array.isArray(this.customDataSource)) {
      // TagBox byKey usually receives an array of keys
      let keys = Array.isArray(key) ? key : [key];
      const found = this.customDataSource.filter((item) => keys.includes(item[this.valueExpr]));
      return found;
    }
    // ----------------------------------------

    if (!this.service) {
      return [];
    }

    const result = await lastValueFrom(
      this.service.getService(this.tagBoxKey, {
        isByKey: true,
        key: key,
      } as TagBoxParam)
    );
    
    return result.data;
  }
}

<dx-tag-box
  #tagBox
  [id]="id"
  [name]="name"
  [width]="width"
  [placeholder]="placeholder"
  [displayExpr]="displayExpr"
  [valueExpr]="valueExpr"
  [searchExpr]="searchExpr"
  [searchEnabled]="searchEnabled"
  [searchTimeout]="searchTimeout"
  [showClearButton]="showClearButton"
  [showSelectionControls]="showSelectionControls"
  [value]="value"
  [dataSource]="dataSource"
  [dropDownOptions]="{ minWidth: '100%', width: dropdownWidth }"
  [maxLength]="maxLength"
  [maxDisplayedTags]="maxDisplayedTags"
  [disabled]="disabled"
  (onValueChanged)="onValueChanged($event)"
  (onEnterKey)="onEnterKey()"
>
</dx-tag-box>
