// packages/react-devextreme/src/lib/components/cnx-number-box/cnx-number-box.tsx
import React, {
    useEffect,
    useRef,
    useState,
    useMemo,
    useCallback,
} from 'react';
import { NumberBox } from 'devextreme-react/number-box';
import type { EventInfo } from 'devextreme/events';
import type { ValueChangedEvent } from 'devextreme/ui/number_box';

export interface CnxNumberBoxProps {
    id?: string;
    name?: string;
    disabled?: boolean;
    value?: number | null;
    format?: string;
    numberType?: 'positive' | 'negative' | 'percent' | 'positivePercent' | null;
    integer?: number;
    max?: number;
    min?: number;
    allowEmpty?: boolean;
    tabIndex?: number;
    disableArrow?: boolean;
    onValueChanged?: (e: ValueChangedEvent & { fromInit?: boolean }) => void;
    onPaste?: (e: any) => void;
    onEnterKey?: () => void;
}

export const CnxNumberBox: React.FC<CnxNumberBoxProps> = ({
    id = '',
    name = '',
    disabled = false,
    value = null,
    format = '#,##0',
    numberType = null,
    integer = 0,
    max,
    min,
    allowEmpty = false,
    tabIndex,
    disableArrow = false,
    onValueChanged,
    onPaste,
    onEnterKey,
}) => {
    const numberBoxRef = useRef<NumberBox>(null);

    const onValueChangedRef = useRef(onValueChanged);
    const onPasteRef = useRef(onPaste);
    const onEnterKeyRef = useRef(onEnterKey);
    useEffect(() => {
        onValueChangedRef.current = onValueChanged;
        onPasteRef.current = onPaste;
        onEnterKeyRef.current = onEnterKey;
    }, [onValueChanged, onPaste, onEnterKey]);
    const [currentFormat, setCurrentFormat] = useState(format);
    const [internalMin, setInternalMin] = useState<number | undefined>(min);
    const [internalMax, setInternalMax] = useState<number | undefined>(max);

    const orgFormat = useRef(format);
    const maxPosibleDigit = 15;

    const checkNumberType = useCallback(() => {
        let computedMax: number | undefined = max;
        let computedMin: number | undefined = min;

        const setMax = (val: number | undefined) => {
            if (max === null || max === undefined) computedMax = val;
        };
        const setMin = (val: number | undefined) => {
            if (min === null || min === undefined) computedMin = val;
        };

        let dotAndDecimalPlace = /\..*/.exec(orgFormat.current)?.[0] || '';
        let decimalPlace = dotAndDecimalPlace.replace('.', '');
        let decimalCount = decimalPlace.length;

        let integerCount = integer;
        if (!integerCount) {
            integerCount = maxPosibleDigit - decimalCount;
            if (!decimalCount) integerCount = 9; // support C# int max value
        }

        if (numberType === 'positive') {
            setMax(
                +(
                    ''.padEnd(integerCount, '9') +
                    '.' +
                    ''.padEnd(decimalCount, '9')
                ),
            );
            setMin(0);
        } else if (numberType === 'negative') {
            setMax(0);
            setMin(
                -+(
                    ''.padEnd(integerCount, '9') +
                    '.' +
                    ''.padEnd(decimalCount, '9')
                ),
            );
        } else if (numberType === 'percent') {
            setMax(100);
            setMin(-100);
        } else if (numberType === 'positivePercent') {
            setMax(100);
            setMin(0);
        } else {
            setMax(
                +(
                    ''.padEnd(integerCount, '9') +
                    '.' +
                    ''.padEnd(decimalCount, '9')
                ),
            );
            setMin(
                -+(
                    ''.padEnd(integerCount, '9') +
                    '.' +
                    ''.padEnd(decimalCount, '9')
                ),
            );
        }

        setInternalMax(computedMax);
        setInternalMin(computedMin);
    }, [integer, max, min, numberType]);

    const checkDisplayValue = useCallback(
        (val: any, isFocus: boolean) => {
            if (isFocus) {
                setCurrentFormat(orgFormat.current);
            } else if (allowEmpty) {
                if (val === 0) {
                    setCurrentFormat(orgFormat.current.replace(/0/g, '#'));
                } else {
                    setCurrentFormat(orgFormat.current);
                }
            }
        },
        [allowEmpty],
    );

    useEffect(() => {
        orgFormat.current = format;
        checkNumberType();
        checkDisplayValue(value, false);
    }, [format, checkNumberType, checkDisplayValue, value]);

    // Handle default initial value of 0 if not allowed empty
    useEffect(() => {
        if ((value === null || value === undefined) && !allowEmpty) {
            setTimeout(() => {
                if (numberBoxRef.current?.instance) {
                    numberBoxRef.current.instance.option('value', 0);
                }
            }, 0);
        }
    }, [value, allowEmpty]);

    // Arrow prevention
    useEffect(() => {
        if (disableArrow && numberBoxRef.current?.instance) {
            numberBoxRef.current.instance.registerKeyHandler(
                'upArrow',
                (e: any) => {
                    e.preventDefault();
                },
            );
            numberBoxRef.current.instance.registerKeyHandler(
                'downArrow',
                (e: any) => {
                    e.preventDefault();
                },
            );
        }
    }, [disableArrow]);

    const handleValueChanged = useCallback(
        (e: ValueChangedEvent) => {
            let _event: any = { ...e };

            if (_event.value === 0 && allowEmpty) {
                _event = { ..._event, value: null };
            }

            // Identify if it was forced by ngAfterViewInit / default zero
            if (!_event.previousValue && _event.value === 0 && !allowEmpty) {
                _event.fromInit = true;
            }

            if (onValueChangedRef.current) {
                onValueChangedRef.current(_event);
            }
        },
        [allowEmpty],
    );

    const handlePaste = useCallback((e: EventInfo<any>) => {
        if (onPasteRef.current) onPasteRef.current(e);
    }, []);

    const handleEnterKey = useCallback((e: EventInfo<any>) => {
        if (onEnterKeyRef.current) onEnterKeyRef.current();
    }, []);

    const handleFocusIn = useCallback(() => {
        checkDisplayValue(value, true);
    }, [checkDisplayValue, value]);

    const handleFocusOut = useCallback(() => {
        checkDisplayValue(value || 0, false);
    }, [checkDisplayValue, value]);

    const elementAttr = useMemo(() => ({ id, name }), [id, name]);

    return (
        <NumberBox
            ref={numberBoxRef}
            elementAttr={elementAttr}
            disabled={disabled}
            value={value === null ? undefined : value}
            format={currentFormat}
            max={internalMax}
            min={internalMin}
            tabIndex={tabIndex}
            onValueChanged={handleValueChanged}
            onPaste={handlePaste}
            onEnterKey={handleEnterKey}
            onFocusIn={handleFocusIn}
            onFocusOut={handleFocusOut}
        />
    );
};

export default CnxNumberBox;

// packages/angular-devextreme/src/lib/components/cnx-number-box/cnx-number-box.component.ts
import {
  AfterViewInit,
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
  ViewChild,
} from '@angular/core';
import { DxNumberBoxComponent } from 'devextreme-angular';

@Component({
  selector: 'cnx-number-box',
  templateUrl: './cnx-number-box.component.html',
  styleUrl: './cnx-number-box.component.css',
  standalone: false,
})
export class CnxNumberBoxComponent implements OnInit, AfterViewInit {
  @ViewChild(DxNumberBoxComponent, { static: false })
  public numberBox!: DxNumberBoxComponent;

  @Input('id')
  public id: string = '';
  @Input('name')
  public name: string = '';

  @Input('disabled')
  public disabled: boolean = false;

  @Input('value')
  set value(val: number | null) {
    this._value = val;
  }
  get value(): number {
    return this._value as any;
  }
  private _value: number | null = null;
  
  @Output('onValueChanged')
  public eventValueChanged: EventEmitter<any> = new EventEmitter();

  @Output('onPaste')
  public eventPaste: EventEmitter<any> = new EventEmitter();

  @Output('onEnterKey')
  public emitEnterKey: EventEmitter<void> = new EventEmitter();

  @Input('format')
  public format: string = '#,##0';
  @Input('numberType')
  public numberType: null | 'positive' | 'negative' | 'percent' | 'positivePercent' = null;
  @Input('integer')
  public integer: number = 0;
  // integer is number before dot(.) ** digit must not exeed 15 when incliuding with decimal digit in format
  // 15 is max digit that dx-number-box can input
  @Input('max')
  public max: number = null as any;
  @Input('min')
  public min: number = null as any;
  @Input('allowEmpty')
  public allowEmpty: boolean = false;
  @Input('tabIndex')
  public tabIndex: number = null as any;

  @Input('disableArrow') disableArrow: boolean = false;

  private _orgFormat: string = '';
  private maxPosibleDigit: number = 15;

  constructor() {}

  public ngOnInit(): void {
    this._orgFormat = this.format;
    this.checkNumberType();
    this.checkDisplayValue(this.value, false);
  }

  public ngAfterViewInit(): void {
    if (this.disableArrow) {
      if (this.numberBox?.instance) {
        this.numberBox.instance.registerKeyHandler('upArrow', (e: any) => {
          e.preventDefault();
        });

        this.numberBox.instance.registerKeyHandler('downArrow', (e: any) => {
          e.preventDefault();
        });
      }
    }

    this.defaultZero();
  }

  public onValueChanged($event: any): void {
    let _event = { ...$event };
    if (_event?.value === 0 && this.allowEmpty) {
      _event = { ..._event, value: null };
    }
    
    // Check if it's from ngAfterViewInit default set
    if (!$event.previousValue && $event.value === 0 && !this.allowEmpty) {
      _event.fromInit = true;
    }
    
    this.eventValueChanged.emit(_event);
  }

  public onPaste($event: any): void {
    this.eventPaste.emit($event);
  }

  public onEnterKey(): void {
    this.emitEnterKey.emit();
  }

  public onFocusIn(): void {
    this.checkDisplayValue(this.value, true);
  }

  public onBlur(): void {
    this.checkDisplayValue(this.value ?? 0, false);
  }

  private checkDisplayValue(value: any, isFocus: boolean): void {
    if (isFocus) {
      this.format = this._orgFormat;
    } else if (this.allowEmpty) {
      if (value === 0) {
        this.format = this.format.replace(/0/g, '#');
      } else {
        this.format = this._orgFormat;
      }
    }
  }

  private defaultZero(): void {
    if (!this.value && !this.allowEmpty) {
      setTimeout(() => {
        if (this.numberBox?.instance) {
          this.numberBox.instance.option('value', 0);
        }
      });
    }
  }

  private checkNumberType(): void {
    const setMax = (value: number | null) => {
      if (!(this.max === null || this.max === undefined)) return;
      this.max = value as any;
    };
    const setMin = (value: number | null) => {
      if (!(this.min === null || this.min === undefined)) return;
      this.min = value as any;
    };

    let dotAndDecimalPlace = /\..*/.exec(this.format)?.[0] || '';
    let decimalPlace = dotAndDecimalPlace.replace('.', '');
    let decimalCount = decimalPlace.length;

    let integerCount = this.integer;
    if (!integerCount) {
      integerCount = this.maxPosibleDigit - decimalCount;
      if (!decimalCount) integerCount = 9; // for support C# int max value
    }

    if (this.numberType == 'positive') {
      setMax(+(''.padEnd(integerCount, '9') + '.' + ''.padEnd(decimalCount, '9')));
      setMin(0);
    } else if (this.numberType == 'negative') {
      setMax(0);
      setMin(-(+(''.padEnd(integerCount, '9') + '.' + ''.padEnd(decimalCount, '9'))));
    } else if (this.numberType == 'percent') {
      setMax(100);
      setMin(-100);
    } else if (this.numberType == 'positivePercent') {
      setMax(100);
      setMin(0);
    } else {
      setMax(+(''.padEnd(integerCount, '9') + '.' + ''.padEnd(decimalCount, '9')));
      setMin(-(+(''.padEnd(integerCount, '9') + '.' + ''.padEnd(decimalCount, '9'))));
    }
  }
}

<dx-number-box
  class="input-number"
  [id]="id"
  [name]="name"
  [format]="format"
  [max]="max"
  [min]="min"
  [tabIndex]="tabIndex"
  [disabled]="disabled"
  [value]="value"
  (onValueChanged)="onValueChanged($event)"
  (onFocusIn)="onFocusIn()"
  (onBlur)="onBlur()"
  (onPaste)="onPaste($event)"
  (onEnterKey)="onEnterKey()"
>
</dx-number-box>
