// packages/angular-devextreme/src/lib/components/cnx-radio-group/cnx-radio-group.component.ts
import {
    ChangeDetectorRef,
    Component,
    EventEmitter,
    Inject,
    Input,
    OnChanges,
    OnInit,
    Optional,
    Output,
    SimpleChanges,
} from '@angular/core';
import {
    RadioGroupKey,
    RadioGroupParam,
    RadioGroupViewModel,
} from '../../models/cnx-radio-group.model';
import { ValueChangedEvent } from 'devextreme/ui/radio_group';
import { lastValueFrom } from 'rxjs';
import { RadioGroupDataProvider } from '../../interfaces/cnx-radio-group.interface';
import { RADIO_GROUP_DATA_PROVIDER } from '../../tokens/cnx-radio-group.token';
import { CascadeRule } from '../../models/cnx-cascade-value';

@Component({
    selector: 'cnx-radio-group',
    templateUrl: './cnx-radio-group.component.html',
    styleUrl: './cnx-radio-group.component.css',
    standalone: false,
})
export class CnxRadioGroupComponent implements OnInit, OnChanges {
    @Input('id') public id: string = '';
    @Input('name') public name: string = '';
    @Input('disabled') public disabled: boolean = false;
    @Input('layout') public layout: 'vertical' | 'horizontal' = 'horizontal';
    @Input('autoDefault') public autoDefault: boolean = true;

    @Input('displayExpr')
    set displayExpr(val: string | null) {
        const _val = val?.toString() || '';
        if (_val && _val !== this.displayExprOption)
            this.displayExprOption = _val;
    }
    get displayExpr(): string {
        return this.displayExprOption;
    }
    public displayExprOption: string = 'text';

    @Input('valueExpr')
    set valueExpr(val: string | null) {
        const _val = val?.toString() || '';
        if (_val && _val !== this._valueExpr) this._valueExpr = _val;
    }
    get valueExpr(): string {
        return this._valueExpr;
    }
    public _valueExpr: string = 'value';

    @Input('radioGroupKey') public radioGroupKey:
        | RadioGroupKey
        | null
        | undefined = null;

    @Input('cascadeRule') public cascadeRule: CascadeRule | CascadeRule[];
    @Input('cascadeBy') public cascadeBy: any;
    @Input('ignoreValue') public ignoreValue: string[] = [];

    @Input('customDataSource')
    public customDataSource?: RadioGroupViewModel[] | any[];

    // @Input('dataSource')
    set dataSource(items: RadioGroupViewModel[] | any[]) {
        this._dataSource = (items || []).map((item) => ({ ...item }));
    }
    get dataSource(): RadioGroupViewModel[] | any[] {
        return this._dataSource;
    }
    private _dataSource: RadioGroupViewModel[] | any[] = [];

    @Input('value')
    set value(val: string | null) {
        this._value = val?.toString() ?? '';
        this.cdr.detectChanges();
    }
    get value(): string {
        return this._value;
    }
    public _value: string = '';

    @Output('onValueChanged')
    public eventValueChanged = new EventEmitter<ValueChangedEvent>();

    constructor(
        @Optional()
        @Inject(RADIO_GROUP_DATA_PROVIDER)
        private service: RadioGroupDataProvider,
        private cdr: ChangeDetectorRef,
    ) {}

    public async ngOnInit(): Promise<void> {
        await this.setupDataSource();
    }

    public async ngOnChanges(changes: SimpleChanges): Promise<void> {
        // ตรวจสอบการเปลี่ยนของ cascadeRule
        const cascadeRuleChange = changes['cascadeRule'];
        if (cascadeRuleChange && !cascadeRuleChange.firstChange) {
            const isDiff =
                JSON.stringify(cascadeRuleChange.currentValue) !==
                JSON.stringify(cascadeRuleChange.previousValue);

            if (isDiff) {
                await this.setupDataSource();
            }
        }

        // ตรวจสอบการเปลี่ยนของ cascadeBy
        const cascadeChange = changes['cascadeBy'];
        if (cascadeChange && !cascadeChange.firstChange) {
            const isDiff =
                JSON.stringify(cascadeChange.currentValue) !==
                JSON.stringify(cascadeChange.previousValue);
            if (isDiff) {
                this.value = '';
                await this.setupDataSource();
            }
        }

        // ตรวจสอบการเปลี่ยนของ customDataSource
        const customChange = changes['customDataSource'];
        if (customChange && !customChange.firstChange) {
            await this.setupDataSource();
        }
    }

    public onValueChanged($event: ValueChangedEvent): void {
        this.eventValueChanged.emit($event);
    }

    private async setupDataSource(): Promise<void> {
        // 1. In-memory customDataSource
        if (this.customDataSource && Array.isArray(this.customDataSource)) {
            let filtered = this.applyCascadeRule(this.customDataSource);
            this.dataSource = this.applyIgnoreValue(filtered);
            this.applyAutoDefault();
            return;
        }

        // 2. Key-based service
        if (this.radioGroupKey && this.service) {
            const result = await lastValueFrom(
                this.service.getService(this.radioGroupKey, {
                    cascadeBy: this.cascadeBy,
                } as RadioGroupParam),
            );
            this.dataSource = this.applyIgnoreValue(result);
            this.applyAutoDefault();
            return;
        }
    }

    private applyCascadeRule(items: RadioGroupViewModel[] | any[]): any[] {
        if (
            !this.cascadeRule ||
            this.cascadeBy === undefined ||
            this.cascadeBy === null
        ) {
            return items;
        }

        const rules = Array.isArray(this.cascadeRule)
            ? this.cascadeRule
            : [this.cascadeRule];

        const filtered = items.filter((item) => {
            return rules.every((rule) => {
                let parentVal: any;

                if (
                    typeof this.cascadeBy === 'object' &&
                    this.cascadeBy !== null
                ) {
                    parentVal = this.cascadeBy[rule.parentKey];
                } else if (
                    this.cascadeBy !== undefined &&
                    this.cascadeBy !== null
                ) {
                    parentVal = this.cascadeBy;
                }
                return item[rule.childKey] === parentVal;
            });
        });

        return filtered;
    }

    private applyIgnoreValue(
        items: RadioGroupViewModel[] | any[],
    ): RadioGroupViewModel[] {
        return !this.ignoreValue?.length
            ? items
            : items.filter(
                  (item) => !this.ignoreValue.includes(item[this._valueExpr]),
              );
    }

    private applyAutoDefault(): void {
        if (this.autoDefault && !this.value && this.dataSource.length > 0) {
            // Use setTimeout to avoid NG0100 when updating parent's value synchronously
            setTimeout(() => {
                this.value = this.dataSource[0]?.[this._valueExpr] ?? '';
                this.cdr.detectChanges();
            });
        }
    }
}

<dx-radio-group
    [id]="'radio_group_' + id"
    [name]="'radio_group_' + name"
    [dataSource]="dataSource"
    [layout]="layout"
    [value]="value"
    [displayExpr]="displayExprOption"
    [valueExpr]="valueExpr"
    [disabled]="disabled"
    (onValueChanged)="onValueChanged($event)"
></dx-radio-group>

// packages/react-devextreme/src/lib/components/cnx-radio-group/cnx-radio-group.tsx
import React, {
    useEffect,
    useState,
    useCallback,
    useMemo,
    useRef,
} from 'react';
import { RadioGroup } from 'devextreme-react/radio-group';
import type { ValueChangedEvent } from 'devextreme/ui/radio_group';
import { useRadioGroupDataProvider } from './cnx-radio-group.context';
import type {
    RadioGroupKey,
    RadioGroupParam,
    RadioGroupViewModel,
} from './cnx-radio-group.types';
import { CascadeRule } from '../cnx-cascade-value.types';

export interface CnxRadioGroupProps {
    id?: string;
    name?: string;
    disabled?: boolean;
    layout?: 'vertical' | 'horizontal';
    autoDefault?: boolean;
    displayExpr?: string;
    valueExpr?: string;
    radioGroupKey?: RadioGroupKey | null;
    cascadeRule?: CascadeRule | CascadeRule[];
    cascadeBy?: any;
    ignoreValue?: string[];
    customDataSource?: any[];
    value?: string | null;
    onValueChanged?: (e: ValueChangedEvent) => void;
}

export const CnxRadioGroup: React.FC<CnxRadioGroupProps> = ({
    id = '',
    name = '',
    disabled = false,
    layout = 'horizontal',
    autoDefault = false,
    displayExpr = 'text',
    valueExpr = 'value',
    radioGroupKey = null,
    cascadeRule,
    cascadeBy,
    ignoreValue,
    customDataSource,
    value,
    onValueChanged,
}) => {
    const service = useRadioGroupDataProvider();
    const [rawData, setRawData] = useState<RadioGroupViewModel[]>([]);

    const valueRef = useRef<string | null | undefined>(value);
    const onValueChangedRef = useRef(onValueChanged);

    useEffect(() => {
        valueRef.current = value;
    }, [value]);

    useEffect(() => {
        onValueChangedRef.current = onValueChanged;
    }, [onValueChanged]);

    // โหลด data
    useEffect(() => {
        const applyCascadeRule = (items: RadioGroupViewModel[]) =>
            !cascadeRule || cascadeBy === undefined || cascadeBy == null
                ? items
                : items.filter((item) => {
                      const rules = Array.isArray(cascadeRule)
                          ? cascadeRule
                          : [cascadeRule];

                      return rules.every((r) => {
                          let parentValue: any;

                          if (
                              typeof cascadeBy === 'object' &&
                              cascadeBy !== null
                          )
                              parentValue = cascadeBy[r.childKey];
                          else if (
                              cascadeBy !== undefined &&
                              cascadeBy !== null
                          )
                              parentValue = cascadeBy;

                          return item[r.childKey] === parentValue;
                      });
                  });

        const applyIgnore = (items: RadioGroupViewModel[]) =>
            ignoreValue?.length
                ? items.filter((item) => !ignoreValue.includes(item[valueExpr]))
                : items;

        const applyAutoDefault = () => {
            if (autoDefault && !value && !disabled && rawData.length > 0) {
                value = rawData[0][valueExpr];
            }
        };

        if (customDataSource && Array.isArray(customDataSource)) {
            const filtered = applyCascadeRule(customDataSource);
            setRawData(applyIgnore(filtered));
            applyAutoDefault();
            return;
        }

        if (radioGroupKey && service) {
            service
                .getService(radioGroupKey, {
                    cascadeBy: cascadeBy,
                } as RadioGroupParam)
                .then((items) => {
                    setRawData(applyIgnore(items || []));
                    applyAutoDefault();
                });
        } else {
            setRawData([]);
        }
    }, [
        radioGroupKey,
        cascadeRule,
        cascadeBy,
        customDataSource,
        ignoreValue,
        valueExpr,
    ]);

    const dataSource = useMemo(() => {
        return rawData;
    }, [rawData]);

    const handleValueChanged = useCallback((e: ValueChangedEvent) => {
        if (onValueChangedRef.current) onValueChangedRef.current(e);
    }, []);

    const elementAttr = useMemo(() => ({ id, name }), [id, name]);

    return (
        <RadioGroup
            elementAttr={elementAttr}
            disabled={disabled}
            layout={layout}
            displayExpr={displayExpr}
            valueExpr={valueExpr}
            dataSource={dataSource}
            value={value}
            onValueChanged={handleValueChanged}
        />
    );
};

export default CnxRadioGroup;
